hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --sistemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("dunst & udiskie")
    hl.exec_cmd("openrgb --startminimized -p Main")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("waybar & hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprlock --grace 0 --no-fade-in")
end)
